[package]
name = "conditional_console_attach"
version = "0.1.0"
edition = "2021"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = [
    "Win32_System_Console",
    "Win32_Storage_FileSystem",
] }


